# Generated by Django 3.0.8 on 2020-07-19 07:28

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErShouFang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('house_url', models.CharField(max_length=500, verbose_name='房源url')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='房源所在城市')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='房源名称')),
                ('total_price', models.FloatField(default=0, verbose_name='总价')),
                ('unit_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='房型')),
                ('square', models.FloatField(default=0, verbose_name='面积')),
                ('detail', django_mysql.models.JSONField(default=dict)),
                ('unit_price', models.FloatField(default=0, verbose_name='单价')),
                ('upload_time', models.DateTimeField(blank=True, null=True, verbose_name='房源挂牌时间')),
                ('orientation', models.CharField(blank=True, max_length=100, null=True, verbose_name='朝向')),
                ('floor', models.CharField(blank=True, max_length=100, null=True, verbose_name='楼层')),
                ('building_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='房屋类型')),
                ('elevator', models.CharField(blank=True, max_length=100, null=True, verbose_name='电梯')),
                ('renovation', models.CharField(blank=True, max_length=100, null=True, verbose_name='装修')),
                ('purpose', models.CharField(blank=True, max_length=100, null=True, verbose_name='用途')),
                ('ownership', models.CharField(blank=True, max_length=100, null=True, verbose_name='权属')),
                ('down_payment_budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='首付预算')),
                ('community', models.CharField(blank=True, max_length=100, null=True, verbose_name='小区')),
                ('room_info', django_mysql.models.JSONField(default=dict)),
                ('introduction', models.TextField(verbose_name='房源介绍')),
                ('trends', models.TextField(verbose_name='房源趋势')),
                ('basic_attributes', models.TextField(verbose_name='基础属性')),
                ('position', models.CharField(blank=True, max_length=300, null=True, verbose_name='位置')),
                ('highlight', models.TextField(verbose_name='房源亮点')),
                ('img_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='房源图片')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
