# Generated by Django 3.0.8 on 2020-07-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ershoufang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ershoufang',
            name='house_url',
        ),
        migrations.RemoveField(
            model_name='ershoufang',
            name='update_time',
        ),
        migrations.AddField(
            model_name='ershoufang',
            name='city_url_id',
            field=models.CharField(default='', max_length=20, verbose_name='城市url_id'),
        ),
        migrations.AddField(
            model_name='ershoufang',
            name='house_url_id',
            field=models.CharField(default='', max_length=100, verbose_name='房源url_id'),
        ),
    ]
