# Generated by Django 3.0.8 on 2020-07-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('start_time', models.DateTimeField(verbose_name='任务开始时间')),
                ('end_time', models.DateTimeField(verbose_name='任务结束时间')),
                ('name', models.CharField(max_length=100, verbose_name='任务名')),
                ('status', models.CharField(max_length=100, verbose_name='任务状态')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
