# Generated by Django 3.0.8 on 2020-07-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskschedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='update_time',
        ),
    ]
