# Generated by Django 3.0.8 on 2020-07-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('start_time', models.DateTimeField(verbose_name='爬虫开始时间')),
                ('end_time', models.DateTimeField(verbose_name='爬虫结束时间')),
                ('house_total', models.PositiveIntegerField(default=0, verbose_name='房源总数')),
                ('city_url', models.CharField(default='', max_length=100, verbose_name='城市')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
