# Generated by Django 3.0.8 on 2020-07-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='city_url',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='house_total',
        ),
        migrations.AddField(
            model_name='statistic',
            name='cost_time',
            field=models.CharField(default='', max_length=100, verbose_name='耗时'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='total',
            field=models.IntegerField(default=0, verbose_name='房源总数'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='type',
            field=models.CharField(choices=[('ershoufang', '二手房'), ('newhouse', '新房'), ('zufang', '租房')], default='ershoufang', max_length=50, verbose_name='房源类型'),
        ),
    ]
