# Generated by Django 3.0.8 on 2020-07-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_auto_20200719_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='update_time',
        ),
    ]
