apiVersion: v1
kind: Service
metadata:
  name: lianjia-service
  namespace: lianjia
spec:
  selector:
    app: lianjia
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: grpc
      port: 9000
